version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: taskapp_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass redis_dev_password
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'redis_dev_password', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redisdata:
